Rails.application.routes.draw do
  resources :wi_offline_msgs
  resources :usersettings
  resources :userprofiles
  resources :userpicks
  resources :usernotes
  resources :userdata
  resources :tokens
  resources :terrains
  resources :spawn_points
  resources :regionwindlights
  resources :regionsettings
  resources :regions
  resources :regionextras
  resources :regionenvironments
  resources :regionbans
  resources :profile_settings
  resources :profile_picks
  resources :profile_notes
  resources :profile_classifieds
  resources :profiles
  resources :primshapes
  resources :prims
  resources :primitems
  resources :os_groups_roles
  resources :os_groups_rolememberships
  resources :os_groups_principals
  resources :os_groups_notices
  resources :os_groups_memberships
  resources :os_groups_invites
  resources :os_groups_groups
  resources :migrations
  resources :landaccesslists
  resources :lands
  resources :inventoryitems
  resources :inventoryfolders
  resources :im_offlines
  resources :hg_traveling_data
  resources :estatebans
  resources :estate_users
  resources :estate_settings
  resources :estate_maps
  resources :estate_managers
  resources :estate_groups
  resources :classifieds
  resources :bakedterrains
  resources :auths
  resources :assets
  resources :user_accounts
  resources :presences
  resources :grid_users
  resources :friends
  resources :avatars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
